### ISSUE TITLE
Please specify MSRV policy

### ISSUE THREAD

**Issue by newpavlov** [paholg/typenum#122]
The latest v1.11 release has broke Minimum Supported Rust Version (MSRV) CI tests for RustCrypto crates (e.g. see RustCrypto/MACs#20). I will not ask you to yank v1.11 and release v2.0 just because of that, but it would be nice if you'll specify in README how you handle MSRV bumps.

**Comment by paholg** [comment]
Woops. I'm sorry. I have removed the nested import braces in 1.11.1 and added Rust 1.22.0 as the MSRV (and added a build on it to Travis).

It should mostly work on as low a version as Rust 1.20.0, but not all tests pass there, so I am not comfortable using it as the MSRV. Since you were using 1.21.0, please let me know if that's a problem.

Otherwise, typenum should continue to work on old Rust versions and this should not happen again.

**Comment by newpavlov** [comment]
Thank you! CI tests for hash functions on Rust 1.21 pass without issues.
