### ISSUE TITLE
Warnings on nightly about mem::uninitialized.

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#126]
There are warnings about the use of `std::mem::uninitialized` on nightly, wanting us to use `MaybeUninit` instead.

However, that would break the minimum Rust version. I think the best approach is the create some zero-sized type and transmute it. I started on that, and it revealed some places where a user misusing typenum (by, say, implementing `Integer` for a type with non-zero size) would get undefined behavior. Using transmutes would reveal such problems, but that means the change is nontrivial.

I am open to any alternative approaches.

**Comment by ecstatic-morse** [comment]
@paholg 

Converting all uses of `std::mem::uninitialized` to `std::mem::zeroed` seems like the path of least resistance here. If backwards compatibility were not an issue, `typenum` could either [seal](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed) the `Integer` trait or make `ConstDefault` (defined below) a supertrait of it.

```rust
trait ConstDefault {
    DEFAULT: Self;
}
```

Converting to `std::mem::zeroed` will likely have no performance overhead since almost all implementers of `Integer` are zero-sized types anyway. Although it can still result in UB if a user implements `Integer` for a non-ZST for which all zeros is not a valid bit pattern, this is no worse than the current situation.

**Comment by programmerjake** [comment]
You could make a `make_zst` function that you replace all uses of `mem::uninitialized` with, but I think either requiring `Default` or sealing `Integer` are better options, since they avoid UB completely (some zero-sized types are things that you shouldn't manufacture out of thin air, such as [`pyo3::Python`](https://docs.rs/pyo3/0.9.0-alpha.1/pyo3/struct.Python.html) or an uninhabited type).

```rust
unsafe fn make_zst<T>() -> T {
    mem::transmute(())
}
```
