### ISSUE TITLE
Docs mention B0 and B1 but don't define them

### ISSUE THREAD

**Issue by sourcefrog** [paholg/typenum#139]
https://docs.rs/typenum/1.11.2/typenum/consts/index.html says

> For unsigned integers, the format is U followed by the number. We define aliases for
> 
> Numbers 0 through 1024 [...]
> `use typenum::{B0, B1, UInt, UTerm};`

**Comment by WaffleLapkin** [comment]
In `1.11.2` doc `B0` and `B1` are declared through `pub use consts::*`:
![image](https://user-images.githubusercontent.com/38225716/82524759-6c8ee780-9b38-11ea-8ca5-30dff9dd7379.png)
![image](https://user-images.githubusercontent.com/38225716/82524788-7ca6c700-9b38-11ea-990e-7b139aa3045e.png)

In `1.12.0` (current latest version) they are declared explicitly: 
![image](https://user-images.githubusercontent.com/38225716/82525013-0bb3df00-9b39-11ea-9080-69bbc2fe79c8.png)
(`pub use consts::*;` got inlined for some reason)


So I think this issue is already resolved.

**Comment by sourcefrog** [comment]
I think so too, thanks.
