### ISSUE TITLE
Performance is still a problem

### ISSUE THREAD

**Issue by llogiq** [paholg/typenum#20]
I just tried to add a test of ` test_uint_op!(U32768 Xor U32768 = U0);` to the uint tests, and I killed the tests after some minutes of waiting. It appears we have linear behavior somewhere.

Absolutely unscientific benchmarks:

|U*N* tested|time
|------------|---------
|64|6.431s
|128|6.979s
|256|8.275s
|512|10.837s
|1024|16.491s
|2048|27.717s
|4096|51.696s
|8192|1m43.607s

This clearly shows (starting from 1024, which appear to start dominating compile time) that when we double the number size, we apparently double the compile time, too.

**Comment by paholg** [comment]
This appears to be due to [this](https://github.com/rust-lang/rust/issues/26325) issue that I found when working on Peano, which I believe caused exponential scaling, so it makes sense that we would have linear scaling.

I have found a fix (for us, not for Peano), where, for each operator, we deal with the four different bit combinations directly instead of relying on bit operations; this drastically reduces the number of `where` clauses needed, and appears to get us to logarithmic scaling.

I should have a PR soon.

**Comment by paholg** [comment]
Unfortunately, these fixes are only temporary. There are warnings in Rust nightly (version 1.5) that many where clauses are missing (essentially that we have to specify that `Unsigned` is implemented for things that we stick into `UInt`s). This warning will become an error in Rust 1.6.

When adding those where clauses, we are back to time issues.

One workaround is to get rid of the `Unsigned` and `Bit` traits, allowing `UInt` to take any two type parameters. I don't like this fix, but it may be our only option.

**Comment by llogiq** [comment]
Yeah, it certainly looks like it. So our `UInt` becomes `UInt<U, B>` without any bounds. While this may seem to cost us a bit of type safety, I don't actually think this is a problem. Compiler errors will probably tend to be more unspecific in case we do something wrong.

**Comment by paholg** [comment]
I'm starting to agree. All of our operators will still be constrained, so while you could make something silly like `UInt<i32, f64>;` you'd get yelled at the moment you tried to do anything with it.

I also don't expect people to use `UInt` directly much, if at all. We have the aliases, and will eventually have a macro that will be much prettier.

Perhaps one day we'll be able to put the bounds back without going from O(log(N)) to O(N). It's crazy that they cost that much.
