### ISSUE TITLE
Question: Inductively implemented trait

### ISSUE THREAD

**Issue by Easyoakland** [paholg/typenum#205]
I'd like to implement a trait inductively. As an example: `trait Inductive {
    type VAL;
}` for `S<U>` is defined in terms of `S<U-1>` down until `S<0>` which has a concrete implementation. This doesn't work for const generics in the stable rust compiler (`generic parameters may not be used in const operations`) so I though to try this crate.
I did this:
```rust
struct S<U>(PhantomData<U>);
impl<U> Inductive for S<U>
where
    U: Sub<U1>,
    S<<U as Sub<U1>>::Output>: Inductive,
{
    type VAL = <S<<U as Sub<U1>>::Output> as Inductive>::VAL;
}
impl Inductive for S<U0> {
    type VAL = u8;
}
```
but this fails with a compiler recursion overflow regardless of the limit on recursion.

I tried a simpler example:
```rust
impl<U> Inductive for U
where
    U: Sub<U1>,
    <U as Sub<U1>>::Output: Inductive,
{
    type VAL = <<U as Sub<U1>>::Output as Inductive>::VAL;
}
impl Inductive for U0 {
    type VAL = U0;
}
```
but this fails with "conflicting implementations of trait `Inductive` for type `UTerm`" ... "upstream crates may add a new impl of trait `std::ops::Sub<typenum::UInt<typenum::UTerm, typenum::B1>>` for type `typenum::UTerm` in future versions".

I can use a macro or something like the below to solve my problem for the values of `S<_>` that I need, but I'm wondering if there's a way to get the above to work with this crate?
```rust
struct _0;
struct S<N>(PhantomData<N>);
impl<N: Inductive> Inductive for S<N> {
    type VAL = <N as Inductive>::VAL;
}
impl Inductive for _0 {
    type VAL = u8;
}
```

**Comment by paholg** [comment]
I'm not sure why your first example fails.

The way I have made this work is to use the structure of unsigned ints in typenum: They are binary encoded, in the form of `UInt<U, B>` where `U` is an unsigned int, `B` is `B0` or `B1`, and `U0` is `UTerm`. And there will never be a leading 0 (`UInt<UTerm, B0>` is invalid, for example).

So, for example,

```rust
U3 = UInt<UInt<UTerm, B1>, B1>;
```

So, rather than using trait bounds in implementations, I use the structure. For example, to test for non-zero, instead of using the bound `U: Sub<U1>`, I just implement for `UInt<U, B>`. To check for even, for example, I would implement a trait for `UInt<U, B0>`.

So, for your example:

```rust
use std::ops::Sub;

use typenum::{Diff, UInt, B1, U0, U7};

trait Inductive {
    type VAL;
}

impl<U, B> Inductive for UInt<U, B>
where
    UInt<U, B>: Sub<B1>,
    Diff<UInt<U, B>, B1>: Inductive,
{
    type VAL = <Diff<UInt<U, B>, B1> as Inductive>::VAL;
}

impl Inductive for U0 {
    type VAL = u8;
}

fn main() {
    let x: <U7 as Inductive>::VAL = 8;
    println!("x: {x}");
}
```

where `Diff` is just short-hand for the output of `Sub`:
```rust
pub type Diff<A, B> = <A as Sub<B>>::Output;
```
And you are free to wrap all that in your `S` struct if you wish.
