### ISSUE TITLE
Derive any / all possible traits?

### ISSUE THREAD

**Issue by paholg** [paholg/typenum#42]
While none of the derivable traits are useful for type-level numbers directly, deriving them allows types that use them to make use of `#[derive]`.

I believe the full list of derivable traits is: `Eq`, `PartialEq`, `Ord`, `PartialOrd`, `Clone`, `Copy`, `Hash`, `Default`, `Zero`, and `Debug`.

I see no reason not to derive all of these for our types, but I may be overlooking something.

**Comment by llogiq** [comment]
I'm fine with `Eq`, `PartialEq`, `PartialOrd`. `Ord`, `Hash`, `Zero` (for `UTerm`, `B0` and `Z0`) and `Debug` (or even `Display`).

However, we need to be careful when implementing any of `Default`, `Clone` or `Copy`, because this will require us to *actually construct instances*. Now there's not exactly a problem with, but then we'd have to either remove the `unreachable!()`s from our various trait implementations and use an actual constructed (zero-sized) value instead, which could mean our machinery may leak into runtime, or we better come up with an implementation that somehow gets around constructing instances.

**Comment by paholg** [comment]
Because struct names double as constructor names, you can do something like
```rust
let x = UTerm;
```
but, for example,
```rust
let x = UInt<UTerm, B1>;
```
gives a compiler error.

In any case, you can already do this:
```rust
let x = B0;
let y = B1;
x | y; // compiler error: unreachable code
// with an unhelpful message that points to the line in bit.rs and nothing to this line.
```
Does deriving copy and clone really change anything? On a side note, should we panic with a more helpful message for those unreachable! calls?

**Comment by paholg** [comment]
For option 3, I don't know how to call a constructor for something like `UInt<UTerm, B1>`, do you?

I also don't see a reason to implement code for something that shouldn't ever happen.

For option 2, unreachable just calls panic with a default message about unreachable code. It can also be passed formatting stuff like panic, so that would be really easy to do.

And it would make sense to put something in the documentation about how you should never create objects. So my vote is for options 1 and 2.
